# Generated by Django 5.0 on 2024-01-02 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coins',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('volume', models.DecimalField(decimal_places=2, max_digits=30)),
                ('twenty_four_hour_percentage', models.DecimalField(decimal_places=2, max_digits=10)),
                ('seven_day_percentage', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
